openapi: 3.0.0
info:
  title: parameters
  version: '1.0'
  description: 'El presente muesta los servicios web (web services) de tipo REST, que están implementados en el sistema de hostal, es importante considerar que la documentación mostrada aqui es para uso interno.'
  contact:
    name: Hans Villaizan
    url: zolymo.blogspot.com
    email: zolymo@cgmail.om
  license:
    name: Apache 2.0
servers:
  - url: 'http://35.247.212.153:8081/parameters'
paths:
  /v1/company/corporate:
    get:
      summary: Lista las principales
      tags:
        - company
      operationId: getCorporate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/companyvo.v1.yaml
              examples:
                lista corporativo:
                  value:
                    createdBy: INITIALCFG
                    createdAt: '05/09/2019 18:43:58'
                    updatedBy: INITIALCFG
                    updatedAt: '05/09/2019 18:43:58'
                    deletedBy: null
                    deletedAt: null
                    activeRow: true
                    nit: XXXXXXXXXXXC
                    name: INOVASTUDIO GROUP SAC
                    commercialName: INOVASTUDIO
                    slogan: Todo nace con una idea
                    abbreviation: AAA
                    idCompany: iNovaStudio
                    contactPeople: Hans Yamamoto
                    logoPath: null
                    idkey: AAA
                    generatedUidc: true
                    masterCompany: '-'
                    organizationType: CORPORATIVO
                    personeryType: JURIDICA
                    companyType: HOSTAL
                    nitType: RUC
                    stakeholderType: CLIENTE_INTERNO
                    userAudit: null
      description: listacorporate
    post:
      summary: ''
      responses:
        '200':
          description: OK
      description: creacorporate
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../common/models/companyvo.v1.yaml
            examples:
              crear:
                value:
                  createdBy: null
                  createdAt: null
                  updatedBy: null
                  updatedAt: null
                  deletedBy: null
                  deletedAt: null
                  activeRow: null
                  nit: '10702433924'
                  name: HOSTAL BLUES
                  commercialName: ''
                  slogan: ''
                  abbreviation: BAX
                  idCompany: Hostal Blues Suc
                  contactPeople: Jhonny Flores Cel 982581458
                  logoPath: null
                  idKey: null
                  generatedUidc: true
                  masterCompany: null
                  organizationType: SUCURSAL
                  personeryType: JURIDICA
                  companyType: HOSTAL
                  nitType: RUC
                  stakeholderType: CLIENTE_INTERNO
                  userAudit:
                    loginname: ZOLYTO
                    corporate: BAA
                    branch: BAX
  /v1/company:
    get:
      summary: Lista las sucursales
      tags:
        - company
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/companyvo.v1.yaml
              examples:
                sucursal: {}
      description: lista sucursales del usuario logueado
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../common/models/userauditvo.v1.yaml
            examples:
              userAudit:
                value:
                  loginname: ZOLYMO
                  corporate: AAA
                  branch: BAA
    post:
      summary: Registra sucursal o corporativo
      tags:
        - company
      responses: {}
components:
  schemas: {}
